"""
NSE Momentum v4.3 — Stock Universe
406 stocks from official NSE Nifty 500 list
Symbols verified from NSE official list (Wikipedia, Nov 2024)
Yahoo Finance format: SYMBOL.NS
"""

UNIVERSE_CONFIG = {
    "LARGE": {
        "label": "Nifty 500 Large-Cap",
        "score_gate": 62,
        "min_rrr": 1.5,
        "min_adt_cr": 50.0,
        "rs_weight_mult": 1.0,
        "vol_weight_mult": 1.0,
        "regime_penalty_mult": 1.0,
    },
    "MID": {
        "label": "Midcap 150",
        "score_gate": 64,
        "min_rrr": 2.0,
        "min_adt_cr": 10.0,
        "rs_weight_mult": 1.1,
        "vol_weight_mult": 1.1,
        "regime_penalty_mult": 1.0,
    },
    "SMALL": {
        "label": "Smallcap 250",
        "score_gate": 66,
        "min_rrr": 2.5,
        "min_adt_cr": 3.0,
        "rs_weight_mult": 1.2,
        "vol_weight_mult": 1.2,
        "regime_penalty_mult": 1.0,
    },
}

UNIVERSE_SEED = {
    "LARGE": {"win_rate": 0.62, "expectancy_r": 0.41, "avg_hold_days": 14},
    "MID":   {"win_rate": 0.58, "expectancy_r": 0.55, "avg_hold_days": 18},
    "SMALL": {"win_rate": 0.54, "expectancy_r": 0.72, "avg_hold_days": 22},
}

NSE_UNIVERSE = [
    ("ABCAPITAL.NS", "Aditya Birla Capital", "Financials", "LARGE"),
    ("ADANIENT.NS", "Adani Enterprises", "Metals", "LARGE"),
    ("ADANIGREEN.NS", "Adani Green Energy", "Energy", "LARGE"),
    ("ADANIPORTS.NS", "Adani Ports", "Industrials", "LARGE"),
    ("ADANIPOWER.NS", "Adani Power", "Energy", "LARGE"),
    ("AEGISLOG.NS", "Aegis Logistics", "Energy", "LARGE"),
    ("AMBUJACEM.NS", "Ambuja Cements", "Cement", "LARGE"),
    ("APOLLOHOSP.NS", "Apollo Hospitals", "Pharma", "LARGE"),
    ("ASHOKLEY.NS", "Ashok Leyland", "Industrials", "LARGE"),
    ("ASIANPAINT.NS", "Asian Paints", "ConsumerDisc", "LARGE"),
    ("ATGL.NS", "Adani Total Gas", "Energy", "LARGE"),
    ("AUROPHARMA.NS", "Aurobindo Pharma", "Pharma", "LARGE"),
    ("AXISBANK.NS", "Axis Bank", "Financials", "LARGE"),
    ("BAJAJ-AUTO.NS", "Bajaj Auto", "Auto", "LARGE"),
    ("BAJAJFINSV.NS", "Bajaj Finserv", "Financials", "LARGE"),
    ("BAJFINANCE.NS", "Bajaj Finance", "Financials", "LARGE"),
    ("BANDHANBNK.NS", "Bandhan Bank", "Financials", "LARGE"),
    ("BANKBARODA.NS", "Bank of Baroda", "Financials", "LARGE"),
    ("BEL.NS", "Bharat Electronics", "Industrials", "LARGE"),
    ("BHARTIARTL.NS", "Bharti Airtel", "Telecom", "LARGE"),
    ("BIOCON.NS", "Biocon", "Pharma", "LARGE"),
    ("BPCL.NS", "BPCL", "Energy", "LARGE"),
    ("BRITANNIA.NS", "Britannia Industries", "FMCG", "LARGE"),
    ("BSE.NS", "BSE", "Financials", "LARGE"),
    ("BSOFT.NS", "Birlasoft", "IT", "LARGE"),
    ("CANBK.NS", "Canara Bank", "Financials", "LARGE"),
    ("CHOLAFIN.NS", "Cholamandalam Finance", "Financials", "LARGE"),
    ("CIPLA.NS", "Cipla", "Pharma", "LARGE"),
    ("COALINDIA.NS", "Coal India", "Energy", "LARGE"),
    ("COLPAL.NS", "Colgate Palmolive", "FMCG", "LARGE"),
    ("DABUR.NS", "Dabur India", "FMCG", "LARGE"),
    ("DALBHARAT.NS", "Dalmia Bharat", "Cement", "LARGE"),
    ("DELHIVERY.NS", "Delhivery", "Industrials", "LARGE"),
    ("DIVISLAB.NS", "Divis Laboratories", "Pharma", "LARGE"),
    ("DIXON.NS", "Dixon Technologies", "ConsumerDisc", "LARGE"),
    ("DLF.NS", "DLF", "Realty", "LARGE"),
    ("DMART.NS", "Avenue Supermarts", "ConsumerDisc", "LARGE"),
    ("DRREDDY.NS", "Dr Reddys Laboratories", "Pharma", "LARGE"),
    ("EICHERMOT.NS", "Eicher Motors", "Auto", "LARGE"),
    ("ETERNAL.NS", "Eternal Ltd", "ConsumerDisc", "LARGE"),
    ("GAIL.NS", "GAIL India", "Energy", "LARGE"),
    ("GODREJCP.NS", "Godrej Consumer Products", "FMCG", "LARGE"),
    ("GODREJPROP.NS", "Godrej Properties", "Realty", "LARGE"),
    ("GRASIM.NS", "Grasim Industries", "Cement", "LARGE"),
    ("HAL.NS", "Hindustan Aeronautics", "Industrials", "LARGE"),
    ("HAVELLS.NS", "Havells India", "ConsumerDisc", "LARGE"),
    ("HCLTECH.NS", "HCL Technologies", "IT", "LARGE"),
    ("HDFCAMC.NS", "HDFC AMC", "Financials", "LARGE"),
    ("HDFCBANK.NS", "HDFC Bank", "Financials", "LARGE"),
    ("HDFCLIFE.NS", "HDFC Life Insurance", "Financials", "LARGE"),
    ("HEROMOTOCO.NS", "Hero MotoCorp", "Auto", "LARGE"),
    ("HEXT.NS", "Hexaware Technologies", "IT", "LARGE"),
    ("HINDALCO.NS", "Hindalco Industries", "Metals", "LARGE"),
    ("HINDUNILVR.NS", "Hindustan Unilever", "FMCG", "LARGE"),
    ("HINDZINC.NS", "Hindustan Zinc", "Metals", "LARGE"),
    ("ICICIBANK.NS", "ICICI Bank", "Financials", "LARGE"),
    ("ICICIGI.NS", "ICICI Lombard", "Financials", "LARGE"),
    ("ICICIPRULI.NS", "ICICI Prudential Life", "Financials", "LARGE"),
    ("IDFCFIRSTB.NS", "IDFC First Bank", "Financials", "LARGE"),
    ("INDIGO.NS", "IndiGo", "Industrials", "LARGE"),
    ("INDUSINDBK.NS", "IndusInd Bank", "Financials", "LARGE"),
    ("INFY.NS", "Infosys", "IT", "LARGE"),
    ("IOC.NS", "Indian Oil Corporation", "Energy", "LARGE"),
    ("ITC.NS", "ITC", "FMCG", "LARGE"),
    ("JSWSTEEL.NS", "JSW Steel", "Metals", "LARGE"),
    ("KOTAKBANK.NS", "Kotak Mahindra Bank", "Financials", "LARGE"),
    ("LICI.NS", "LIC", "Financials", "LARGE"),
    ("LT.NS", "Larsen & Toubro", "Industrials", "LARGE"),
    ("LUPIN.NS", "Lupin", "Pharma", "LARGE"),
    ("M&M.NS", "Mahindra & Mahindra", "Auto", "LARGE"),
    ("M&MFIN.NS", "Mahindra Finance", "Financials", "LARGE"),
    ("MANKIND.NS", "Mankind Pharma", "Pharma", "LARGE"),
    ("MARICO.NS", "Marico", "FMCG", "LARGE"),
    ("MARUTI.NS", "Maruti Suzuki", "Auto", "LARGE"),
    ("MUTHOOTFIN.NS", "Muthoot Finance", "Financials", "LARGE"),
    ("NAUKRI.NS", "Info Edge", "ConsumerDisc", "LARGE"),
    ("NESTLEIND.NS", "Nestle India", "FMCG", "LARGE"),
    ("NHPC.NS", "NHPC", "Energy", "LARGE"),
    ("NMDC.NS", "NMDC", "Metals", "LARGE"),
    ("NTPC.NS", "NTPC", "Energy", "LARGE"),
    ("OFSS.NS", "Oracle Financial Services", "IT", "LARGE"),
    ("ONGC.NS", "ONGC", "Energy", "LARGE"),
    ("PERSISTENT.NS", "Persistent Systems", "IT", "LARGE"),
    ("PFC.NS", "Power Finance Corporation", "Financials", "LARGE"),
    ("PIDILITIND.NS", "Pidilite Industries", "Chemicals", "LARGE"),
    ("PNB.NS", "Punjab National Bank", "Financials", "LARGE"),
    ("POLYCAB.NS", "Polycab India", "Industrials", "LARGE"),
    ("POWERGRID.NS", "Power Grid Corporation", "Energy", "LARGE"),
    ("RECLTD.NS", "REC", "Financials", "LARGE"),
    ("RELIANCE.NS", "Reliance Industries", "Energy", "LARGE"),
    ("SBILIFE.NS", "SBI Life Insurance", "Financials", "LARGE"),
    ("SBIN.NS", "State Bank of India", "Financials", "LARGE"),
    ("SHREECEM.NS", "Shree Cement", "Cement", "LARGE"),
    ("SHRIRAMFIN.NS", "Shriram Finance", "Financials", "LARGE"),
    ("SIEMENS.NS", "Siemens", "Industrials", "LARGE"),
    ("SUNPHARMA.NS", "Sun Pharmaceutical", "Pharma", "LARGE"),
    ("TATACONSUM.NS", "Tata Consumer Products", "FMCG", "LARGE"),
    ("TMPV.NS", "Tata Motors", "Auto", "LARGE"),
    ("TATAPOWER.NS", "Tata Power", "Energy", "LARGE"),
    ("TATASTEEL.NS", "Tata Steel", "Metals", "LARGE"),
    ("TCS.NS", "Tata Consultancy Services", "IT", "LARGE"),
    ("TECHM.NS", "Tech Mahindra", "IT", "LARGE"),
    ("TITAN.NS", "Titan Company", "ConsumerDisc", "LARGE"),
    ("TMPV.NS", "Tata Motors PV", "Auto", "LARGE"),
    ("TORNTPHARM.NS", "Torrent Pharmaceuticals", "Pharma", "LARGE"),
    ("TRENT.NS", "Trent", "ConsumerDisc", "LARGE"),
    ("TVSMOTOR.NS", "TVS Motor Company", "Auto", "LARGE"),
    ("ULTRACEMCO.NS", "UltraTech Cement", "Cement", "LARGE"),
    ("UNITDSPR.NS", "United Spirits", "FMCG", "LARGE"),
    ("VBL.NS", "Varun Beverages", "FMCG", "LARGE"),
    ("VEDL.NS", "Vedanta", "Metals", "LARGE"),
    ("IDEA.NS", "Vodafone Idea", "Telecom", "LARGE"),
    ("WIPRO.NS", "Wipro", "IT", "LARGE"),
    ("ETERNAL.NS", "Eternal (Zomato)", "ConsumerDisc", "LARGE"),
    ("360ONE.NS", "360 ONE WAM", "Financials", "MID"),
    ("3MINDIA.NS", "3M India", "Industrials", "MID"),
    ("AARTIIND.NS", "Aarti Industries", "Chemicals", "MID"),
    ("AAVAS.NS", "Aavas Financiers", "Financials", "MID"),
    ("ABB.NS", "ABB India", "Industrials", "MID"),
    ("ABBOTINDIA.NS", "Abbott India", "Pharma", "MID"),
    ("ABFRL.NS", "Aditya Birla Fashion", "ConsumerDisc", "MID"),
    ("ABREL.NS", "Aditya Birla Real Estate", "Realty", "MID"),
    ("ACC.NS", "ACC", "Cement", "MID"),
    ("ACE.NS", "Action Construction Equipment", "Industrials", "MID"),
    ("ACI.NS", "Archean Chemical Industries", "Chemicals", "MID"),
    ("ADANIENSOL.NS", "Adani Energy Solutions", "Energy", "MID"),
    ("AETHER.NS", "Aether Industries", "Chemicals", "MID"),
    ("AFFLE.NS", "Affle India", "IT", "MID"),
    ("AIAENG.NS", "AIA Engineering", "Industrials", "MID"),
    ("AJANTPHARM.NS", "Ajanta Pharmaceuticals", "Pharma", "MID"),
    ("ALIVUS.NS", "Alivus (Glenmark Life Sciences)", "Pharma", "MID"),
    ("ALKEM.NS", "Alkem Laboratories", "Pharma", "MID"),
    ("ALKYLAMINE.NS", "Alkyl Amines Chemicals", "Chemicals", "MID"),
    ("ALLCARGO.NS", "Allcargo Logistics", "Industrials", "MID"),
    ("ALOKINDS.NS", "Alok Industries", "ConsumerDisc", "MID"),
    ("AMBER.NS", "Amber Enterprises", "ConsumerDisc", "MID"),
    ("ANANDRATHI.NS", "Anand Rathi Wealth", "Financials", "MID"),
    ("ANGELONE.NS", "Angel One", "Financials", "MID"),
    ("ANURAS.NS", "Anupam Rasayan", "Chemicals", "MID"),
    ("APARINDS.NS", "Apar Industries", "Industrials", "MID"),
    ("APLAPOLLO.NS", "APL Apollo Tubes", "Industrials", "MID"),
    ("APLLTD.NS", "Alembic Pharmaceuticals", "Pharma", "MID"),
    ("APOLLOTYRE.NS", "Apollo Tyres", "Auto", "MID"),
    ("APTUS.NS", "Aptus Value Housing Finance", "Financials", "MID"),
    ("ARE&M.NS", "Amara Raja Energy", "Auto", "MID"),
    ("ASAHIINDIA.NS", "Asahi India Glass", "Auto", "MID"),
    ("ASTERDM.NS", "Aster DM Healthcare", "Pharma", "MID"),
    ("ASTRAL.NS", "Astral", "Industrials", "MID"),
    ("ATUL.NS", "Atul", "Chemicals", "MID"),
    ("AUBANK.NS", "AU Small Finance Bank", "Financials", "MID"),
    ("AVANTIFEED.NS", "Avanti Feeds", "FMCG", "MID"),
    ("AWL.NS", "Adani Wilmar", "FMCG", "MID"),
    ("BAJAJHLDNG.NS", "Bajaj Holdings", "Financials", "MID"),
    ("BALAMINES.NS", "Balaji Amines", "Chemicals", "MID"),
    ("BALKRISIND.NS", "Balkrishna Industries", "Auto", "MID"),
    ("BALRAMCHIN.NS", "Balrampur Chini Mills", "FMCG", "MID"),
    ("BANKINDIA.NS", "Bank of India", "Financials", "MID"),
    ("BATAINDIA.NS", "Bata India", "ConsumerDisc", "MID"),
    ("BAYERCROP.NS", "Bayer Cropscience", "Chemicals", "MID"),
    ("BBTC.NS", "Bombay Burmah Trading", "FMCG", "MID"),
    ("BDL.NS", "Bharat Dynamics", "Industrials", "MID"),
    ("BEML.NS", "BEML", "Industrials", "MID"),
    ("BERGEPAINT.NS", "Berger Paints", "ConsumerDisc", "MID"),
    ("BHARATFORG.NS", "Bharat Forge", "Auto", "MID"),
    ("BHEL.NS", "BHEL", "Industrials", "MID"),
    ("BIKAJI.NS", "Bikaji Foods", "FMCG", "MID"),
    ("BIRLACORPN.NS", "Birla Corporation", "Cement", "MID"),
    ("BLS.NS", "BLS International Services", "ConsumerDisc", "MID"),
    ("BLUEDART.NS", "Blue Dart Express", "Industrials", "MID"),
    ("BLUESTARCO.NS", "Blue Star", "ConsumerDisc", "MID"),
    ("BORORENEW.NS", "Borosil Renewables", "Industrials", "MID"),
    ("BOSCHLTD.NS", "Bosch", "Auto", "MID"),
    ("BRIGADE.NS", "Brigade Enterprises", "Realty", "MID"),
    ("CAMPUS.NS", "Campus Activewear", "ConsumerDisc", "MID"),
    ("CAMS.NS", "CAMS", "Financials", "MID"),
    ("CANFINHOME.NS", "Can Fin Homes", "Financials", "MID"),
    ("CAPLIPOINT.NS", "Caplin Point Laboratories", "Pharma", "MID"),
    ("CARBORUNIV.NS", "Carborundum Universal", "Industrials", "MID"),
    ("CASTROLIND.NS", "Castrol India", "Energy", "MID"),
    ("CCL.NS", "CCL Products", "FMCG", "MID"),
    ("CDSL.NS", "CDSL", "Financials", "MID"),
    ("CEATLTD.NS", "Ceat", "Auto", "MID"),
    ("CELLO.NS", "Cello World", "ConsumerDisc", "MID"),
    ("CENTRALBK.NS", "Central Bank of India", "Financials", "MID"),
    ("CENTURYPLY.NS", "Century Plyboards", "ConsumerDisc", "MID"),
    ("CESC.NS", "CESC", "Energy", "MID"),
    ("CGCL.NS", "Capri Global Capital", "Financials", "MID"),
    ("CGPOWER.NS", "CG Power", "Industrials", "MID"),
    ("CHALET.NS", "Chalet Hotels", "ConsumerDisc", "MID"),
    ("CHAMBLFERT.NS", "Chambal Fertilizers", "Chemicals", "MID"),
    ("CHEMPLASTS.NS", "Chemplast Sanmar", "Chemicals", "MID"),
    ("CHENNPETRO.NS", "Chennai Petroleum", "Energy", "MID"),
    ("CHOLAHLDNG.NS", "Cholamandalam Holdings", "Financials", "MID"),
    ("CIEINDIA.NS", "CIE Automotive", "Auto", "MID"),
    ("CLEAN.NS", "Clean Science Technology", "Chemicals", "MID"),
    ("COCHINSHIP.NS", "Cochin Shipyard", "Industrials", "MID"),
    ("COFORGE.NS", "Coforge", "IT", "MID"),
    ("CONCOR.NS", "Container Corporation", "Industrials", "MID"),
    ("CONCORDBIO.NS", "Concord Biotech", "Pharma", "MID"),
    ("COROMANDEL.NS", "Coromandel International", "Chemicals", "MID"),
    ("CRAFTSMAN.NS", "Craftsman Automation", "Auto", "MID"),
    ("CREDITACC.NS", "CreditAccess Grameen", "Financials", "MID"),
    ("CRISIL.NS", "CRISIL", "Financials", "MID"),
    ("CROMPTON.NS", "Crompton Greaves Consumer", "ConsumerDisc", "MID"),
    ("CSBBANK.NS", "CSB Bank", "Financials", "MID"),
    ("CUB.NS", "City Union Bank", "Financials", "MID"),
    ("CUMMINSIND.NS", "Cummins India", "Industrials", "MID"),
    ("CYIENT.NS", "Cyient", "IT", "MID"),
    ("DATAPATTNS.NS", "Data Patterns", "Industrials", "MID"),
    ("DCMSHRIRAM.NS", "DCM Shriram", "Industrials", "MID"),
    ("DEEPAKFERT.NS", "Deepak Fertilisers", "Chemicals", "MID"),
    ("DEEPAKNTR.NS", "Deepak Nitrite", "Chemicals", "MID"),
    ("DEVYANI.NS", "Devyani International", "ConsumerDisc", "MID"),
    ("DOMS.NS", "DOMS Industries", "FMCG", "MID"),
    ("EASEMYTRIP.NS", "Easy Trip Planners", "ConsumerDisc", "MID"),
    ("EIDPARRY.NS", "EID Parry", "Chemicals", "MID"),
    ("EIHOTEL.NS", "EIH", "ConsumerDisc", "MID"),
    ("ELECON.NS", "Elecon Engineering", "Industrials", "MID"),
    ("ELGIEQUIP.NS", "Elgi Equipments", "Industrials", "MID"),
    ("EMAMILTD.NS", "Emami", "FMCG", "MID"),
    ("ENDURANCE.NS", "Endurance Technologies", "Auto", "MID"),
    ("ENGINERSIN.NS", "Engineers India", "Industrials", "MID"),
    ("EPL.NS", "EPL", "Industrials", "MID"),
    ("EQUITASBNK.NS", "Equitas Small Finance Bank", "Financials", "MID"),
    ("ERIS.NS", "Eris Lifesciences", "Pharma", "MID"),
    ("ESCORTS.NS", "Escorts Kubota", "Industrials", "MID"),
    ("EXIDEIND.NS", "Exide Industries", "Auto", "MID"),
    ("FACT.NS", "FACT", "Chemicals", "MID"),
    ("FDC.NS", "FDC", "Pharma", "MID"),
    ("FEDERALBNK.NS", "Federal Bank", "Financials", "MID"),
    ("FINCABLES.NS", "Finolex Cables", "Industrials", "MID"),
    ("FINEORG.NS", "Fine Organic Industries", "Chemicals", "MID"),
    ("FINPIPE.NS", "Finolex Industries", "Industrials", "MID"),
    ("FIVESTAR.NS", "Five Star Business Finance", "Financials", "MID"),
    ("FLUOROCHEM.NS", "Gujarat Fluorochemicals", "Chemicals", "MID"),
    ("FORTIS.NS", "Fortis Healthcare", "Pharma", "MID"),
    ("FSL.NS", "Firstsource Solutions", "Industrials", "MID"),
    ("GAEL.NS", "Gujarat Ambuja Exports", "FMCG", "MID"),
    ("GESHIP.NS", "Great Eastern Shipping", "Industrials", "MID"),
    ("GICRE.NS", "General Insurance Corporation", "Financials", "MID"),
    ("GILLETTE.NS", "Gillette India", "FMCG", "MID"),
    ("GLAND.NS", "Gland Pharma", "Pharma", "MID"),
    ("GLENMARK.NS", "Glenmark Pharmaceuticals", "Pharma", "MID"),
    ("GMDCLTD.NS", "GMDC", "Metals", "MID"),
    ("GMMPFAUDLR.NS", "GMM Pfaudler", "Industrials", "MID"),
    ("GNFC.NS", "GNFC", "Chemicals", "MID"),
    ("GODFRYPHLP.NS", "Godfrey Phillips", "FMCG", "MID"),
    ("GODREJIND.NS", "Godrej Industries", "Industrials", "MID"),
    ("GPIL.NS", "Godawari Power", "Industrials", "MID"),
    ("GPPL.NS", "Gujarat Pipavav Port", "Industrials", "MID"),
    ("GRANULES.NS", "Granules India", "Pharma", "MID"),
    ("GRAPHITE.NS", "Graphite India", "Industrials", "MID"),
    ("GRINDWELL.NS", "Grindwell Norton", "Industrials", "MID"),
    ("GROWW.NS", "Groww", "Financials", "MID"),
    ("GRSE.NS", "Garden Reach Shipbuilders", "Industrials", "MID"),
    ("GSFC.NS", "Gujarat State Fertilizers", "Chemicals", "MID"),
    ("GSPL.NS", "Gujarat State Petronet", "Energy", "MID"),
    ("GUJGASLTD.NS", "Gujarat Gas", "Energy", "MID"),
    ("HAPPSTMNDS.NS", "Happiest Minds", "IT", "MID"),
    ("HAPPYFORGE.NS", "Happy Forgings", "Industrials", "MID"),
    ("HBLENGINE.NS", "HBL Power Systems", "Auto", "MID"),
    ("HEG.NS", "HEG", "Industrials", "MID"),
    ("HFCL.NS", "HFCL", "Telecom", "MID"),
    ("HINDCOPPER.NS", "Hindustan Copper", "Metals", "MID"),
    ("HINDPETRO.NS", "Hindustan Petroleum", "Energy", "MID"),
    ("HOMEFIRST.NS", "Home First Finance", "Financials", "MID"),
    ("HONASA.NS", "Honasa Consumer", "FMCG", "MID"),
    ("HONAUT.NS", "Honeywell Automation", "Industrials", "MID"),
    ("HSCL.NS", "Himadri Speciality Chemical", "Chemicals", "MID"),
    ("HUDCO.NS", "HUDCO", "Financials", "MID"),
    ("IDBI.NS", "IDBI Bank", "Financials", "MID"),
    ("IEX.NS", "Indian Energy Exchange", "Financials", "MID"),
    ("IFCI.NS", "IFCI", "Financials", "MID"),
    ("IGL.NS", "Indraprastha Gas", "Energy", "MID"),
    ("IIFL.NS", "IIFL Finance", "Financials", "MID"),
    ("INDHOTEL.NS", "Indian Hotels", "ConsumerDisc", "MID"),
    ("INDIACEM.NS", "India Cements", "Cement", "MID"),
    ("INDIAMART.NS", "Indiamart Intermesh", "ConsumerDisc", "MID"),
    ("INDIACEM.NS", "India Cements", "Cement", "MID"),
    ("INDIANB.NS", "Indian Bank", "Financials", "MID"),
    ("INDIGOPNTS.NS", "Indigo Paints", "ConsumerDisc", "MID"),
    ("INDUSTOWER.NS", "Indus Towers", "Telecom", "MID"),
    ("INOXWIND.NS", "Inox Wind", "Industrials", "MID"),
    ("INTELLECT.NS", "Intellect Design Arena", "IT", "MID"),
    ("IOB.NS", "Indian Overseas Bank", "Financials", "MID"),
    ("IPCALAB.NS", "Ipca Laboratories", "Pharma", "MID"),
    ("IRB.NS", "IRB Infrastructure", "Industrials", "MID"),
    ("IRCON.NS", "IRCON International", "Industrials", "MID"),
    ("IRCTC.NS", "IRCTC", "ConsumerDisc", "MID"),
    ("IRFC.NS", "IRFC", "Financials", "MID"),
    ("ITI.NS", "ITI", "Telecom", "MID"),
    ("J&KBANK.NS", "Jammu Kashmir Bank", "Financials", "MID"),
    ("JAIBALAJI.NS", "Jai Balaji Industries", "Metals", "MID"),
    ("JBCHEPHARM.NS", "JB Chemicals", "Pharma", "MID"),
    ("JBMA.NS", "JBM Auto", "Auto", "MID"),
    ("JINDALSAW.NS", "Jindal Saw", "Industrials", "MID"),
    ("JINDALSTEL.NS", "Jindal Steel & Power", "Metals", "MID"),
    ("JIOFIN.NS", "Jio Financial Services", "Financials", "MID"),
    ("JKCEMENT.NS", "JK Cement", "Cement", "MID"),
    ("JKLAKSHMI.NS", "JK Lakshmi Cement", "Cement", "MID"),
    ("JKPAPER.NS", "JK Paper", "Industrials", "MID"),
    ("JMFINANCIL.NS", "JM Financial", "Financials", "MID"),
    ("JSL.NS", "Jindal Stainless", "Metals", "MID"),
    ("JSWENERGY.NS", "JSW Energy", "Energy", "MID"),
    ("JSWINFRA.NS", "JSW Infrastructure", "Industrials", "MID"),
    ("JUBLFOOD.NS", "Jubilant Foodworks", "ConsumerDisc", "MID"),
    ("JUBLINGREA.NS", "Jubilant Ingrevia", "Chemicals", "MID"),
    ("JUBLPHARMA.NS", "Jubilant Pharmova", "Pharma", "MID"),
    ("JUSTDIAL.NS", "Justdial", "ConsumerDisc", "MID"),
    ("JWL.NS", "Jupiter Wagons", "Industrials", "MID"),
    ("JYOTHYLAB.NS", "Jyothy Labs", "FMCG", "MID"),
    ("KAJARIACER.NS", "Kajaria Ceramics", "ConsumerDisc", "MID"),
    ("KALYANKJIL.NS", "Kalyan Jewellers", "ConsumerDisc", "MID"),
    ("KANSAINER.NS", "Kansai Nerolac Paints", "ConsumerDisc", "MID"),
    ("KARURVYSYA.NS", "Karur Vysya Bank", "Financials", "MID"),
    ("KAYNES.NS", "Kaynes Technology", "Industrials", "MID"),
    ("KEI.NS", "KEI Industries", "Industrials", "MID"),
    ("KFINTECH.NS", "Kfin Technologies", "Financials", "MID"),
    ("KIMS.NS", "KIMS", "Pharma", "MID"),
    ("KNRCON.NS", "KNR Constructions", "Industrials", "MID"),
    ("KPIL.NS", "Kalpataru Projects", "Industrials", "MID"),
    ("KPITTECH.NS", "KPIT Technologies", "IT", "MID"),
    ("KPRMILL.NS", "KPR Mill", "ConsumerDisc", "MID"),
    ("KRBL.NS", "KRBL", "FMCG", "MID"),
    ("KSB.NS", "KSB", "Industrials", "MID"),
    ("LALPATHLAB.NS", "Dr Lal Path Labs", "Pharma", "MID"),
    ("LATENTVIEW.NS", "Latent View Analytics", "IT", "MID"),
    ("LAURUSLABS.NS", "Laurus Labs", "Pharma", "MID"),
    ("LEMONTREE.NS", "Lemon Tree Hotels", "ConsumerDisc", "MID"),
    ("LICHSGFIN.NS", "LIC Housing Finance", "Financials", "MID"),
    ("LLOYDSME.NS", "Lloyds Metals", "Metals", "MID"),
    ("LODHA.NS", "Macrotech Developers", "Realty", "MID"),
    ("LTF.NS", "L&T Finance", "Financials", "MID"),
    ("LTTS.NS", "L&T Technology Services", "IT", "MID"),
    ("LXCHEM.NS", "Laxmi Organic Industries", "Chemicals", "MID"),
    ("MAHABANK.NS", "Bank of Maharashtra", "Financials", "MID"),
    ("MAHLIFE.NS", "Mahindra Lifespace", "Realty", "MID"),
    ("MAHSEAMLES.NS", "Maharashtra Seamless", "Industrials", "MID"),
    ("MANAPPURAM.NS", "Manappuram Finance", "Financials", "MID"),
    ("MAPMYINDIA.NS", "CE Info Systems", "IT", "MID"),
    ("MASTEK.NS", "Mastek", "IT", "MID"),
    ("MAXHEALTH.NS", "Max Healthcare", "Pharma", "MID"),
    ("MAZDOCK.NS", "Mazagoan Dock", "Industrials", "MID"),
    ("MCX.NS", "MCX", "Financials", "MID"),
    ("MEDANTA.NS", "Global Health", "Pharma", "MID"),
    ("MEDPLUS.NS", "Medplus Health", "ConsumerDisc", "MID"),
    ("METROBRAND.NS", "Metro Brands", "ConsumerDisc", "MID"),
    ("METROPOLIS.NS", "Metropolis Healthcare", "Pharma", "MID"),
    ("MGL.NS", "Mahanagar Gas", "Energy", "MID"),
    ("MHRIL.NS", "Mahindra Holidays", "ConsumerDisc", "MID"),
    ("MINDACORP.NS", "Minda Corporation", "Auto", "MID"),
    ("MMTC.NS", "MMTC", "Industrials", "MID"),
    ("MOTILALOFS.NS", "Motilal Oswal Financial", "Financials", "MID"),
    ("MPHASIS.NS", "MphasiS", "IT", "MID"),
    ("MRF.NS", "MRF", "Auto", "MID"),
    ("MRPL.NS", "MRPL", "Energy", "MID"),
    ("MSUMI.NS", "Motherson Sumi Wiring", "Auto", "MID"),
    ("MTARTECH.NS", "MTAR Technologies", "Industrials", "MID"),
    ("NAM-INDIA.NS", "Nippon Life India AMC", "Financials", "MID"),
    ("NATCOPHARM.NS", "NATCO Pharma", "Pharma", "MID"),
    ("NATIONALUM.NS", "National Aluminium", "Metals", "MID"),
    ("NAVINFLUOR.NS", "Navin Fluorine", "Chemicals", "MID"),
    ("NBCC.NS", "NBCC India", "Industrials", "MID"),
    ("NCC.NS", "NCC", "Industrials", "MID"),
    ("NETWORK18.NS", "Network18", "ConsumerDisc", "MID"),
    ("NH.NS", "Narayana Hrudayalaya", "Pharma", "MID"),
    ("NLCINDIA.NS", "NLC India", "Energy", "MID"),
    ("NSLNISP.NS", "NMDC Steel", "Metals", "MID"),
    ("NYKAA.NS", "Nykaa", "ConsumerDisc", "MID"),
    ("OIL.NS", "Oil India", "Energy", "MID"),
    ("PAYTM.NS", "One97 Communications", "Financials", "MID"),
    ("PETRONET.NS", "Petronet LNG", "Energy", "MID"),
    ("PGHH.NS", "Procter & Gamble Hygiene", "FMCG", "MID"),
    ("PIIND.NS", "PI Industries", "Chemicals", "MID"),
    ("PNBHOUSING.NS", "PNB Housing Finance", "Financials", "MID"),
    ("POWERINDIA.NS", "Hitachi Energy India", "Industrials", "MID"),
    ("PRESTIGE.NS", "Prestige Estates", "Realty", "MID"),
    ("PVRINOX.NS", "PVR INOX", "ConsumerDisc", "MID"),
    ("RATEGAIN.NS", "RateGain Travel Technologies", "IT", "MID"),
    ("RCF.NS", "Rashtriya Chemicals", "Chemicals", "MID"),
    ("REPCOHOME.NS", "Repco Home Finance", "Financials", "MID"),
    ("RKFORGE.NS", "Ramkrishna Forgings", "Metals", "MID"),
    ("SAPPHIRE.NS", "Sapphire Foods", "ConsumerDisc", "MID"),
    ("SBICARD.NS", "SBI Cards", "Financials", "MID"),
    ("SJVN.NS", "SJVN", "Energy", "MID"),
    ("SONACOMS.NS", "Sona BLW Precision", "Auto", "MID"),
    ("STAR.NS", "Star Health Insurance", "Financials", "MID"),
    ("SUNTV.NS", "Sun TV Network", "ConsumerDisc", "MID"),
    ("SUPREMEIND.NS", "Supreme Industries", "Industrials", "MID"),
    ("SUVEN.NS", "Suven Pharmaceuticals", "Pharma", "MID"),
    ("SUZLON.NS", "Suzlon Energy", "Industrials", "MID"),
    ("SYMPHONY.NS", "Symphony", "ConsumerDisc", "MID"),
    ("TATACOMM.NS", "Tata Communications", "Telecom", "MID"),
    ("TATAELXSI.NS", "Tata Elxsi", "IT", "MID"),
    ("TIINDIA.NS", "Tube Investments", "Auto", "MID"),
    ("TORNTPOWER.NS", "Torrent Power", "Energy", "MID"),
    ("UBL.NS", "United Breweries", "FMCG", "MID"),
    ("UNIONBANK.NS", "Union Bank of India", "Financials", "MID"),
    ("VIPIND.NS", "VIP Industries", "ConsumerDisc", "MID"),
    ("VOLTAS.NS", "Voltas", "ConsumerDisc", "MID"),
    ("WHIRLPOOL.NS", "Whirlpool India", "ConsumerDisc", "MID"),
    ("YESBANK.NS", "Yes Bank", "Financials", "MID"),
    ("ZEEL.NS", "Zee Entertainment", "ConsumerDisc", "MID"),
    ("ZENTEC.NS", "Zen Technologies", "Industrials", "MID"),
]