"""
NSE Momentum v6.2 — Stock Universe
500 stocks from official NSE Nifty 500 list (expanded from 401, prior session)
Symbols verified from NSE official list (Wikipedia, Nov 2024)
Yahoo Finance format: SYMBOL.NS
"""

UNIVERSE_CONFIG = {
    "LARGE": {
        "label": "Nifty 500 Large-Cap",
        "score_gate": 62,
        "min_rrr": 1.5,
        "min_adt_cr": 50.0,
        "rs_weight_mult": 1.0,
        "vol_weight_mult": 1.0,
        "regime_penalty_mult": 1.0,
    },
    "MID": {
        "label": "Midcap 150",
        "score_gate": 64,
        "min_rrr": 2.0,
        "min_adt_cr": 10.0,
        "rs_weight_mult": 1.1,
        "vol_weight_mult": 1.1,
        "regime_penalty_mult": 1.0,
    },
    "SMALL": {
        "label": "Smallcap 250",
        "score_gate": 66,
        "min_rrr": 2.5,
        "min_adt_cr": 3.0,
        "rs_weight_mult": 1.2,
        "vol_weight_mult": 1.2,
        "regime_penalty_mult": 1.0,
    },
}

UNIVERSE_SEED = {
    "LARGE": {"win_rate": 0.62, "expectancy_r": 0.41, "avg_hold_days": 14},
    "MID":   {"win_rate": 0.58, "expectancy_r": 0.55, "avg_hold_days": 18},
    "SMALL": {"win_rate": 0.54, "expectancy_r": 0.72, "avg_hold_days": 22},
}

NSE_UNIVERSE = [
    ("ABB.NS", "ABB India Ltd.", "Industrials", "LARGE"),
    ("ADANIENSOL.NS", "Adani Energy Solutions Ltd.", "Energy", "LARGE"),
    ("ADANIENT.NS", "Adani Enterprises Ltd.", "Metals", "LARGE"),
    ("ADANIGREEN.NS", "Adani Green Energy Ltd.", "Energy", "LARGE"),
    ("ADANIPORTS.NS", "Adani Ports and Special Economic Zone Ltd.", "Industrials", "LARGE"),
    ("ADANIPOWER.NS", "Adani Power Ltd.", "Energy", "LARGE"),
    ("AMBUJACEM.NS", "Ambuja Cements Ltd.", "Cement", "LARGE"),
    ("APOLLOHOSP.NS", "Apollo Hospitals Enterprise Ltd.", "Pharma", "LARGE"),
    ("ASIANPAINT.NS", "Asian Paints Ltd.", "ConsumerDisc", "LARGE"),
    ("DMART.NS", "Avenue Supermarts Ltd.", "ConsumerDisc", "LARGE"),
    ("AXISBANK.NS", "Axis Bank Ltd.", "Financials", "LARGE"),
    ("BAJAJ-AUTO.NS", "Bajaj Auto Ltd.", "Auto", "LARGE"),
    ("BAJFINANCE.NS", "Bajaj Finance Ltd.", "Financials", "LARGE"),
    ("BAJAJFINSV.NS", "Bajaj Finserv Ltd.", "Financials", "LARGE"),
    ("BAJAJHLDNG.NS", "Bajaj Holdings & Investment Ltd.", "Financials", "LARGE"),
    ("BANKBARODA.NS", "Bank of Baroda", "Financials", "LARGE"),
    ("BEL.NS", "Bharat Electronics Ltd.", "Industrials", "LARGE"),
    ("BPCL.NS", "Bharat Petroleum Corporation Ltd.", "Energy", "LARGE"),
    ("BHARTIARTL.NS", "Bharti Airtel Ltd.", "Telecom", "LARGE"),
    ("BOSCHLTD.NS", "Bosch Ltd.", "Auto", "LARGE"),
    ("BRITANNIA.NS", "Britannia Industries Ltd.", "FMCG", "LARGE"),
    ("CGPOWER.NS", "CG Power and Industrial Solutions Ltd.", "Industrials", "LARGE"),
    ("CANBK.NS", "Canara Bank", "Financials", "LARGE"),
    ("CHOLAFIN.NS", "Cholamandalam Investment and Finance Company Ltd.", "Financials", "LARGE"),
    ("CIPLA.NS", "Cipla Ltd.", "Pharma", "LARGE"),
    ("COALINDIA.NS", "Coal India Ltd.", "Energy", "LARGE"),
    ("CUMMINSIND.NS", "Cummins India Ltd.", "Industrials", "LARGE"),
    ("DLF.NS", "DLF Ltd.", "Realty", "LARGE"),
    ("DIVISLAB.NS", "Divi's Laboratories Ltd.", "Pharma", "LARGE"),
    ("DRREDDY.NS", "Dr. Reddy's Laboratories Ltd.", "Pharma", "LARGE"),
    ("EICHERMOT.NS", "Eicher Motors Ltd.", "Auto", "LARGE"),
    ("ETERNAL.NS", "Eternal Ltd.", "ConsumerDisc", "LARGE"),
    ("GAIL.NS", "GAIL (India) Ltd.", "Energy", "LARGE"),
    ("GODREJCP.NS", "Godrej Consumer Products Ltd.", "FMCG", "LARGE"),
    ("GRASIM.NS", "Grasim Industries Ltd.", "Cement", "LARGE"),
    ("HCLTECH.NS", "HCL Technologies Ltd.", "IT", "LARGE"),
    ("HDFCAMC.NS", "HDFC Asset Management Company Ltd.", "Financials", "LARGE"),
    ("HDFCBANK.NS", "HDFC Bank Ltd.", "Financials", "LARGE"),
    ("HDFCLIFE.NS", "HDFC Life Insurance Company Ltd.", "Financials", "LARGE"),
    ("HINDALCO.NS", "Hindalco Industries Ltd.", "Metals", "LARGE"),
    ("HAL.NS", "Hindustan Aeronautics Ltd.", "Industrials", "LARGE"),
    ("HINDUNILVR.NS", "Hindustan Unilever Ltd.", "FMCG", "LARGE"),
    ("HINDZINC.NS", "Hindustan Zinc Ltd.", "Metals", "LARGE"),
    ("HYUNDAI.NS", "Hyundai Motor India Ltd.", "Automobile and Auto Components", "LARGE"),
    ("ICICIBANK.NS", "ICICI Bank Ltd.", "Financials", "LARGE"),
    ("ITC.NS", "ITC Ltd.", "FMCG", "LARGE"),
    ("INDHOTEL.NS", "Indian Hotels Co. Ltd.", "ConsumerDisc", "LARGE"),
    ("IOC.NS", "Indian Oil Corporation Ltd.", "Energy", "LARGE"),
    ("IRFC.NS", "Indian Railway Finance Corporation Ltd.", "Financials", "LARGE"),
    ("INFY.NS", "Infosys Ltd.", "IT", "LARGE"),
    ("INDIGO.NS", "InterGlobe Aviation Ltd.", "Industrials", "LARGE"),
    ("JSWSTEEL.NS", "JSW Steel Ltd.", "Metals", "LARGE"),
    ("JINDALSTEL.NS", "Jindal Steel Ltd.", "Metals", "LARGE"),
    ("JIOFIN.NS", "Jio Financial Services Ltd.", "Financials", "LARGE"),
    ("KOTAKBANK.NS", "Kotak Mahindra Bank Ltd.", "Financials", "LARGE"),
    ("LTM.NS", "LTM Ltd.", "Information Technology", "LARGE"),
    ("LT.NS", "Larsen & Toubro Ltd.", "Industrials", "LARGE"),
    ("LODHA.NS", "Lodha Developers Ltd.", "Realty", "LARGE"),
    ("M&M.NS", "Mahindra & Mahindra Ltd.", "Auto", "LARGE"),
    ("MARUTI.NS", "Maruti Suzuki India Ltd.", "Auto", "LARGE"),
    ("MAXHEALTH.NS", "Max Healthcare Institute Ltd.", "Pharma", "LARGE"),
    ("MAZDOCK.NS", "Mazagoan Dock Shipbuilders Ltd.", "Industrials", "LARGE"),
    ("MUTHOOTFIN.NS", "Muthoot Finance Ltd.", "Financials", "LARGE"),
    ("NTPC.NS", "NTPC Ltd.", "Energy", "LARGE"),
    ("NESTLEIND.NS", "Nestle India Ltd.", "FMCG", "LARGE"),
    ("ONGC.NS", "Oil & Natural Gas Corporation Ltd.", "Energy", "LARGE"),
    ("PIDILITIND.NS", "Pidilite Industries Ltd.", "Chemicals", "LARGE"),
    ("PFC.NS", "Power Finance Corporation Ltd.", "Financials", "LARGE"),
    ("POWERGRID.NS", "Power Grid Corporation of India Ltd.", "Energy", "LARGE"),
    ("PNB.NS", "Punjab National Bank", "Financials", "LARGE"),
    ("RECLTD.NS", "REC Ltd.", "Financials", "LARGE"),
    ("RELIANCE.NS", "Reliance Industries Ltd.", "Energy", "LARGE"),
    ("SBILIFE.NS", "SBI Life Insurance Company Ltd.", "Financials", "LARGE"),
    ("MOTHERSON.NS", "Samvardhana Motherson International Ltd.", "Automobile and Auto Components", "LARGE"),
    ("SHREECEM.NS", "Shree Cement Ltd.", "Cement", "LARGE"),
    ("SHRIRAMFIN.NS", "Shriram Finance Ltd.", "Financials", "LARGE"),
    ("ENRIN.NS", "Siemens Energy India Ltd.", "Capital Goods", "LARGE"),
    ("SIEMENS.NS", "Siemens Ltd.", "Industrials", "LARGE"),
    ("SOLARINDS.NS", "Solar Industries India Ltd.", "Chemicals", "LARGE"),
    ("SBIN.NS", "State Bank of India", "Financials", "LARGE"),
    ("SUNPHARMA.NS", "Sun Pharmaceutical Industries Ltd.", "Pharma", "LARGE"),
    ("TVSMOTOR.NS", "TVS Motor Company Ltd.", "Auto", "LARGE"),
    ("TATACAP.NS", "Tata Capital Ltd.", "Financial Services", "LARGE"),
    ("TCS.NS", "Tata Consultancy Services Ltd.", "IT", "LARGE"),
    ("TATACONSUM.NS", "Tata Consumer Products Ltd.", "FMCG", "LARGE"),
    ("TMCV.NS", "Tata Motors Ltd.", "Capital Goods", "LARGE"),
    ("TMPV.NS", "Tata Motors Passenger Vehicles Ltd.", "Auto", "LARGE"),
    ("TATAPOWER.NS", "Tata Power Co. Ltd.", "Energy", "LARGE"),
    ("TATASTEEL.NS", "Tata Steel Ltd.", "Metals", "LARGE"),
    ("TECHM.NS", "Tech Mahindra Ltd.", "IT", "LARGE"),
    ("TITAN.NS", "Titan Company Ltd.", "ConsumerDisc", "LARGE"),
    ("TORNTPHARM.NS", "Torrent Pharmaceuticals Ltd.", "Pharma", "LARGE"),
    ("TRENT.NS", "Trent Ltd.", "ConsumerDisc", "LARGE"),
    ("ULTRACEMCO.NS", "UltraTech Cement Ltd.", "Cement", "LARGE"),
    ("UNIONBANK.NS", "Union Bank of India", "Financials", "LARGE"),
    ("UNITDSPR.NS", "United Spirits Ltd.", "FMCG", "LARGE"),
    ("VBL.NS", "Varun Beverages Ltd.", "FMCG", "LARGE"),
    ("VEDL.NS", "Vedanta Ltd.", "Metals", "LARGE"),
    ("WIPRO.NS", "Wipro Ltd.", "IT", "LARGE"),
    ("ZYDUSLIFE.NS", "Zydus Lifesciences Ltd.", "Healthcare", "LARGE"),
    ("360ONE.NS", "360 ONE WAM Ltd.", "Financials", "MID"),
    ("3MINDIA.NS", "3M India Ltd.", "Industrials", "MID"),
    ("ACC.NS", "ACC Ltd.", "Cement", "MID"),
    ("AIAENG.NS", "AIA Engineering Ltd.", "Industrials", "MID"),
    ("APLAPOLLO.NS", "APL Apollo Tubes Ltd.", "Industrials", "MID"),
    ("AUBANK.NS", "AU Small Finance Bank Ltd.", "Financials", "MID"),
    ("AWL.NS", "AWL Agri Business Ltd.", "FMCG", "MID"),
    ("ABBOTINDIA.NS", "Abbott India Ltd.", "Pharma", "MID"),
    ("ATGL.NS", "Adani Total Gas Ltd.", "Energy", "MID"),
    ("ABCAPITAL.NS", "Aditya Birla Capital Ltd.", "Financials", "MID"),
    ("AJANTPHARM.NS", "Ajanta Pharmaceuticals Ltd.", "Pharma", "MID"),
    ("ALKEM.NS", "Alkem Laboratories Ltd.", "Pharma", "MID"),
    ("ANTHEM.NS", "Anthem Biosciences Ltd.", "Healthcare", "MID"),
    ("APARINDS.NS", "Apar Industries Ltd.", "Industrials", "MID"),
    ("APOLLOTYRE.NS", "Apollo Tyres Ltd.", "Auto", "MID"),
    ("ASHOKLEY.NS", "Ashok Leyland Ltd.", "Industrials", "MID"),
    ("ASTRAL.NS", "Astral Ltd.", "Industrials", "MID"),
    ("AUROPHARMA.NS", "Aurobindo Pharma Ltd.", "Pharma", "MID"),
    ("AIIL.NS", "Authum Investment & Infrastructure Ltd.", "Financial Services", "MID"),
    ("BSE.NS", "BSE Ltd.", "Financials", "MID"),
    ("BAJAJHFL.NS", "Bajaj Housing Finance Ltd.", "Financial Services", "MID"),
    ("BALKRISIND.NS", "Balkrishna Industries Ltd.", "Auto", "MID"),
    ("BANKINDIA.NS", "Bank of India", "Financials", "MID"),
    ("MAHABANK.NS", "Bank of Maharashtra", "Financials", "MID"),
    ("BERGEPAINT.NS", "Berger Paints India Ltd.", "ConsumerDisc", "MID"),
    ("BDL.NS", "Bharat Dynamics Ltd.", "Industrials", "MID"),
    ("BHARATFORG.NS", "Bharat Forge Ltd.", "Auto", "MID"),
    ("BHEL.NS", "Bharat Heavy Electricals Ltd.", "Industrials", "MID"),
    ("BHARTIHEXA.NS", "Bharti Hexacom Ltd.", "Telecommunication", "MID"),
    ("GROWW.NS", "Billionbrains Garage Ventures Ltd.", "Financials", "MID"),
    ("BIOCON.NS", "Biocon Ltd.", "Pharma", "MID"),
    ("BLUESTARCO.NS", "Blue Star Ltd.", "ConsumerDisc", "MID"),
    ("CRISIL.NS", "CRISIL Ltd.", "Financials", "MID"),
    ("COCHINSHIP.NS", "Cochin Shipyard Ltd.", "Industrials", "MID"),
    ("COFORGE.NS", "Coforge Ltd.", "IT", "MID"),
    ("COLPAL.NS", "Colgate Palmolive (India) Ltd.", "FMCG", "MID"),
    ("CONCOR.NS", "Container Corporation of India Ltd.", "Industrials", "MID"),
    ("COROMANDEL.NS", "Coromandel International Ltd.", "Chemicals", "MID"),
    ("DABUR.NS", "Dabur India Ltd.", "FMCG", "MID"),
    ("DALBHARAT.NS", "Dalmia Bharat Ltd.", "Cement", "MID"),
    ("DIXON.NS", "Dixon Technologies (India) Ltd.", "ConsumerDisc", "MID"),
    ("ENDURANCE.NS", "Endurance Technologies Ltd.", "Auto", "MID"),
    ("ESCORTS.NS", "Escorts Kubota Ltd.", "Industrials", "MID"),
    ("EXIDEIND.NS", "Exide Industries Ltd.", "Auto", "MID"),
    ("NYKAA.NS", "FSN E-Commerce Ventures Ltd.", "ConsumerDisc", "MID"),
    ("FEDERALBNK.NS", "Federal Bank Ltd.", "Financials", "MID"),
    ("FORTIS.NS", "Fortis Healthcare Ltd.", "Pharma", "MID"),
    ("GVT&D.NS", "GE Vernova T&D India Ltd.", "Capital Goods", "MID"),
    ("GMRAIRPORT.NS", "GMR Airports Ltd.", "Services", "MID"),
    ("GICRE.NS", "General Insurance Corporation of India", "Financials", "MID"),
    ("GLAXO.NS", "Glaxosmithkline Pharmaceuticals Ltd.", "Healthcare", "MID"),
    ("GLENMARK.NS", "Glenmark Pharmaceuticals Ltd.", "Pharma", "MID"),
    ("MEDANTA.NS", "Global Health Ltd.", "Pharma", "MID"),
    ("GODFRYPHLP.NS", "Godfrey Phillips India Ltd.", "FMCG", "MID"),
    ("GODREJIND.NS", "Godrej Industries Ltd.", "Industrials", "MID"),
    ("GODREJPROP.NS", "Godrej Properties Ltd.", "Realty", "MID"),
    ("FLUOROCHEM.NS", "Gujarat Fluorochemicals Ltd.", "Chemicals", "MID"),
    ("HDBFS.NS", "HDB Financial Services Ltd.", "Financial Services", "MID"),
    ("HAVELLS.NS", "Havells India Ltd.", "ConsumerDisc", "MID"),
    ("HEROMOTOCO.NS", "Hero MotoCorp Ltd.", "Auto", "MID"),
    ("HEXT.NS", "Hexaware Technologies Ltd.", "IT", "MID"),
    ("HINDPETRO.NS", "Hindustan Petroleum Corporation Ltd.", "Energy", "MID"),
    ("POWERINDIA.NS", "Hitachi Energy India Ltd.", "Industrials", "MID"),
    ("HONAUT.NS", "Honeywell Automation India Ltd.", "Industrials", "MID"),
    ("HUDCO.NS", "Housing & Urban Development Corporation Ltd.", "Financials", "MID"),
    ("ICICIGI.NS", "ICICI Lombard General Insurance Company Ltd.", "Financials", "MID"),
    ("ICICIAMC.NS", "ICICI Prudential Asset Management Company Ltd.", "Financial Services", "MID"),
    ("ICICIPRULI.NS", "ICICI Prudential Life Insurance Company Ltd.", "Financials", "MID"),
    ("IDFCFIRSTB.NS", "IDFC First Bank Ltd.", "Financials", "MID"),
    ("ITCHOTELS.NS", "ITC Hotels Ltd.", "Consumer Services", "MID"),
    ("INDIANB.NS", "Indian Bank", "Financials", "MID"),
    ("IRCTC.NS", "Indian Railway Catering And Tourism Corporation Ltd.", "ConsumerDisc", "MID"),
    ("IREDA.NS", "Indian Renewable Energy Development Agency Ltd.", "Financial Services", "MID"),
    ("INDUSTOWER.NS", "Indus Towers Ltd.", "Telecom", "MID"),
    ("INDUSINDBK.NS", "IndusInd Bank Ltd.", "Financials", "MID"),
    ("NAUKRI.NS", "Info Edge (India) Ltd.", "ConsumerDisc", "MID"),
    ("IPCALAB.NS", "Ipca Laboratories Ltd.", "Pharma", "MID"),
    ("JKCEMENT.NS", "J.K. Cement Ltd.", "Cement", "MID"),
    ("JSWENERGY.NS", "JSW Energy Ltd.", "Energy", "MID"),
    ("JSWINFRA.NS", "JSW Infrastructure Ltd.", "Industrials", "MID"),
    ("JSL.NS", "Jindal Stainless Ltd.", "Metals", "MID"),
    ("JUBLFOOD.NS", "Jubilant Foodworks Ltd.", "ConsumerDisc", "MID"),
    ("KPRMILL.NS", "K.P.R. Mill Ltd.", "ConsumerDisc", "MID"),
    ("KEI.NS", "KEI Industries Ltd.", "Industrials", "MID"),
    ("KPITTECH.NS", "KPIT Technologies Ltd.", "IT", "MID"),
    ("KALYANKJIL.NS", "Kalyan Jewellers India Ltd.", "ConsumerDisc", "MID"),
    ("LTF.NS", "L&T Finance Ltd.", "Financials", "MID"),
    ("LTTS.NS", "L&T Technology Services Ltd.", "IT", "MID"),
    ("LGEINDIA.NS", "LG Electronics India Ltd.", "Consumer Durables", "MID"),
    ("LICHSGFIN.NS", "LIC Housing Finance Ltd.", "Financials", "MID"),
    ("LAURUSLABS.NS", "Laurus Labs Ltd.", "Pharma", "MID"),
    ("LENSKART.NS", "Lenskart Solutions Ltd.", "Consumer Services", "MID"),
    ("LICI.NS", "Life Insurance Corporation of India", "Financials", "MID"),
    ("LINDEINDIA.NS", "Linde India Ltd.", "Chemicals", "MID"),
    ("LLOYDSME.NS", "Lloyds Metals And Energy Ltd.", "Metals", "MID"),
    ("LUPIN.NS", "Lupin Ltd.", "Pharma", "MID"),
    ("MRF.NS", "MRF Ltd.", "Auto", "MID"),
    ("M&MFIN.NS", "Mahindra & Mahindra Financial Services Ltd.", "Financials", "MID"),
    ("MANKIND.NS", "Mankind Pharma Ltd.", "Pharma", "MID"),
    ("MARICO.NS", "Marico Ltd.", "FMCG", "MID"),
    ("MFSL.NS", "Max Financial Services Ltd.", "Financial Services", "MID"),
    ("MOTILALOFS.NS", "Motilal Oswal Financial Services Ltd.", "Financials", "MID"),
    ("MPHASIS.NS", "MphasiS Ltd.", "IT", "MID"),
    ("MCX.NS", "Multi Commodity Exchange of India Ltd.", "Financials", "MID"),
    ("NHPC.NS", "NHPC Ltd.", "Energy", "MID"),
    ("NLCINDIA.NS", "NLC India Ltd.", "Energy", "MID"),
    ("NMDC.NS", "NMDC Ltd.", "Metals", "MID"),
    ("NTPCGREEN.NS", "NTPC Green Energy Ltd.", "Power", "MID"),
    ("NATIONALUM.NS", "National Aluminium Co. Ltd.", "Metals", "MID"),
    ("NAM-INDIA.NS", "Nippon Life India Asset Management Ltd.", "Financials", "MID"),
    ("OBEROIRLTY.NS", "Oberoi Realty Ltd.", "Realty", "MID"),
    ("OIL.NS", "Oil India Ltd.", "Energy", "MID"),
    ("PAYTM.NS", "One 97 Communications Ltd.", "Financials", "MID"),
    ("OFSS.NS", "Oracle Financial Services Software Ltd.", "IT", "MID"),
    ("POLICYBZR.NS", "PB Fintech Ltd.", "Financial Services", "MID"),
    ("PIIND.NS", "PI Industries Ltd.", "Chemicals", "MID"),
    ("PAGEIND.NS", "Page Industries Ltd.", "Textiles", "MID"),
    ("PATANJALI.NS", "Patanjali Foods Ltd.", "Fast Moving Consumer Goods", "MID"),
    ("PERSISTENT.NS", "Persistent Systems Ltd.", "IT", "MID"),
    ("PETRONET.NS", "Petronet LNG Ltd.", "Energy", "MID"),
    ("PHOENIXLTD.NS", "Phoenix Mills Ltd.", "Realty", "MID"),
    ("POLYCAB.NS", "Polycab India Ltd.", "Industrials", "MID"),
    ("PREMIERENE.NS", "Premier Energies Ltd.", "Capital Goods", "MID"),
    ("PRESTIGE.NS", "Prestige Estates Projects Ltd.", "Realty", "MID"),
    ("RADICO.NS", "Radico Khaitan Ltd", "Fast Moving Consumer Goods", "MID"),
    ("RVNL.NS", "Rail Vikas Nigam Ltd.", "Construction", "MID"),
    ("SBICARD.NS", "SBI Cards and Payment Services Ltd.", "Financials", "MID"),
    ("SJVN.NS", "SJVN Ltd.", "Energy", "MID"),
    ("SRF.NS", "SRF Ltd.", "Chemicals", "MID"),
    ("SCHAEFFLER.NS", "Schaeffler India Ltd.", "Automobile and Auto Components", "MID"),
    ("SAIL.NS", "Steel Authority of India Ltd.", "Metals & Mining", "MID"),
    ("SUNDARMFIN.NS", "Sundaram Finance Ltd.", "Financial Services", "MID"),
    ("SUPREMEIND.NS", "Supreme Industries Ltd.", "Industrials", "MID"),
    ("SUZLON.NS", "Suzlon Energy Ltd.", "Industrials", "MID"),
    ("SWIGGY.NS", "Swiggy Ltd.", "Consumer Services", "MID"),
    ("TATACOMM.NS", "Tata Communications Ltd.", "Telecom", "MID"),
    ("TATAELXSI.NS", "Tata Elxsi Ltd.", "IT", "MID"),
    ("TATAINVEST.NS", "Tata Investment Corporation Ltd.", "Financial Services", "MID"),
    ("NIACL.NS", "The New India Assurance Company Ltd.", "Financial Services", "MID"),
    ("THERMAX.NS", "Thermax Ltd.", "Capital Goods", "MID"),
    ("TORNTPOWER.NS", "Torrent Power Ltd.", "Energy", "MID"),
    ("TIINDIA.NS", "Tube Investments of India Ltd.", "Auto", "MID"),
    ("UNOMINDA.NS", "UNO Minda Ltd.", "Automobile and Auto Components", "MID"),
    ("UPL.NS", "UPL Ltd.", "Chemicals", "MID"),
    ("UBL.NS", "United Breweries Ltd.", "FMCG", "MID"),
    ("VMM.NS", "Vishal Mega Mart Ltd.", "Consumer Services", "MID"),
    ("IDEA.NS", "Vodafone Idea Ltd.", "Telecom", "MID"),
    ("VOLTAS.NS", "Voltas Ltd.", "ConsumerDisc", "MID"),
    ("WAAREEENER.NS", "Waaree Energies Ltd.", "Capital Goods", "MID"),
    ("YESBANK.NS", "Yes Bank Ltd.", "Financials", "MID"),
    ("ACMESOLAR.NS", "ACME Solar Holdings Ltd.", "Power", "SMALL"),
    ("AADHARHFC.NS", "Aadhar Housing Finance Ltd.", "Financial Services", "SMALL"),
    ("AARTIIND.NS", "Aarti Industries Ltd.", "Chemicals", "SMALL"),
    ("AAVAS.NS", "Aavas Financiers Ltd.", "Financials", "SMALL"),
    ("ACE.NS", "Action Construction Equipment Ltd.", "Industrials", "SMALL"),
    ("ACUTAAS.NS", "Acutaas Chemicals Ltd.", "Healthcare", "SMALL"),
    ("ABFRL.NS", "Aditya Birla Fashion and Retail Ltd.", "ConsumerDisc", "SMALL"),
    ("ABLBL.NS", "Aditya Birla Lifestyle Brands Ltd.", "Consumer Services", "SMALL"),
    ("ABREL.NS", "Aditya Birla Real Estate Ltd.", "Realty", "SMALL"),
    ("ABSLAMC.NS", "Aditya Birla Sun Life AMC Ltd.", "Financial Services", "SMALL"),
    ("CPPLUS.NS", "Aditya Infotech Ltd.", "Capital Goods", "SMALL"),
    ("AEGISLOG.NS", "Aegis Logistics Ltd.", "Energy", "SMALL"),
    ("AEGISVOPAK.NS", "Aegis Vopak Terminals Ltd.", "Oil Gas & Consumable Fuels", "SMALL"),
    ("AFCONS.NS", "Afcons Infrastructure Ltd.", "Construction", "SMALL"),
    ("AFFLE.NS", "Affle 3i Ltd.", "IT", "SMALL"),
    ("ABDL.NS", "Allied Blenders and Distillers Ltd.", "Fast Moving Consumer Goods", "SMALL"),
    ("ARE&M.NS", "Amara Raja Energy & Mobility Ltd.", "Auto", "SMALL"),
    ("AMBER.NS", "Amber Enterprises India Ltd.", "ConsumerDisc", "SMALL"),
    ("ANANDRATHI.NS", "Anand Rathi Wealth Ltd.", "Financials", "SMALL"),
    ("ANANTRAJ.NS", "Anant Raj Ltd.", "Realty", "SMALL"),
    ("ANGELONE.NS", "Angel One Ltd.", "Financials", "SMALL"),
    ("ANURAS.NS", "Anupam Rasayan India Ltd.", "Chemicals", "SMALL"),
    ("APTUS.NS", "Aptus Value Housing Finance India Ltd.", "Financials", "SMALL"),
    ("ASAHIINDIA.NS", "Asahi India Glass Ltd.", "Auto", "SMALL"),
    ("ASTERDM.NS", "Aster DM Healthcare Ltd.", "Pharma", "SMALL"),
    ("ATHERENERG.NS", "Ather Energy Ltd.", "Automobile and Auto Components", "SMALL"),
    ("ATUL.NS", "Atul Ltd.", "Chemicals", "SMALL"),
    ("BEML.NS", "BEML Ltd.", "Industrials", "SMALL"),
    ("BLS.NS", "BLS International Services Ltd.", "ConsumerDisc", "SMALL"),
    ("BALRAMCHIN.NS", "Balrampur Chini Mills Ltd.", "FMCG", "SMALL"),
    ("BANDHANBNK.NS", "Bandhan Bank Ltd.", "Financials", "SMALL"),
    ("BATAINDIA.NS", "Bata India Ltd.", "ConsumerDisc", "SMALL"),
    ("BAYERCROP.NS", "Bayer Cropscience Ltd.", "Chemicals", "SMALL"),
    ("BELRISE.NS", "Belrise Industries Ltd.", "Automobile and Auto Components", "SMALL"),
    ("BIKAJI.NS", "Bikaji Foods International Ltd.", "FMCG", "SMALL"),
    ("BSOFT.NS", "Birlasoft Ltd.", "IT", "SMALL"),
    ("BLUEDART.NS", "Blue Dart Express Ltd.", "Industrials", "SMALL"),
    ("BLUEJET.NS", "Blue Jet Healthcare Ltd.", "Healthcare", "SMALL"),
    ("BBTC.NS", "Bombay Burmah Trading Corporation Ltd.", "FMCG", "SMALL"),
    ("FIRSTCRY.NS", "Brainbees Solutions Ltd.", "Consumer Services", "SMALL"),
    ("BRIGADE.NS", "Brigade Enterprises Ltd.", "Realty", "SMALL"),
    ("MAPMYINDIA.NS", "C.E. Info Systems Ltd.", "IT", "SMALL"),
    ("CCL.NS", "CCL Products (I) Ltd.", "FMCG", "SMALL"),
    ("CESC.NS", "CESC Ltd.", "Energy", "SMALL"),
    ("CIEINDIA.NS", "CIE Automotive India Ltd.", "Auto", "SMALL"),
    ("CANFINHOME.NS", "Can Fin Homes Ltd.", "Financials", "SMALL"),
    ("CANHLIFE.NS", "Canara HSBC Life Insurance Company Ltd.", "Financial Services", "SMALL"),
    ("CAPLIPOINT.NS", "Caplin Point Laboratories Ltd.", "Pharma", "SMALL"),
    ("CGCL.NS", "Capri Global Capital Ltd.", "Financials", "SMALL"),
    ("CARBORUNIV.NS", "Carborundum Universal Ltd.", "Industrials", "SMALL"),
    ("CARTRADE.NS", "Cartrade Tech Ltd.", "Consumer Services", "SMALL"),
    ("CASTROLIND.NS", "Castrol India Ltd.", "Energy", "SMALL"),
    ("CEATLTD.NS", "Ceat Ltd.", "Auto", "SMALL"),
    ("CEMPRO.NS", "Cemindia Projects Ltd.", "Construction", "SMALL"),
    ("CENTRALBK.NS", "Central Bank of India", "Financials", "SMALL"),
    ("CDSL.NS", "Central Depository Services (India) Ltd.", "Financials", "SMALL"),
    ("CHALET.NS", "Chalet Hotels Ltd.", "ConsumerDisc", "SMALL"),
    ("CHAMBLFERT.NS", "Chambal Fertilizers & Chemicals Ltd.", "Chemicals", "SMALL"),
    ("CHENNPETRO.NS", "Chennai Petroleum Corporation Ltd.", "Energy", "SMALL"),
    ("CHOICEIN.NS", "Choice International Ltd.", "Financial Services", "SMALL"),
    ("CHOLAHLDNG.NS", "Cholamandalam Financial Holdings Ltd.", "Financials", "SMALL"),
    ("CUB.NS", "City Union Bank Ltd.", "Financials", "SMALL"),
    ("CLEAN.NS", "Clean Science and Technology Ltd.", "Chemicals", "SMALL"),
    ("COHANCE.NS", "Cohance Lifesciences Ltd.", "Healthcare", "SMALL"),
    ("CAMS.NS", "Computer Age Management Services Ltd.", "Financials", "SMALL"),
    ("CONCORDBIO.NS", "Concord Biotech Ltd.", "Pharma", "SMALL"),
    ("CRAFTSMAN.NS", "Craftsman Automation Ltd.", "Auto", "SMALL"),
    ("CREDITACC.NS", "CreditAccess Grameen Ltd.", "Financials", "SMALL"),
    ("CROMPTON.NS", "Crompton Greaves Consumer Electricals Ltd.", "ConsumerDisc", "SMALL"),
    ("CYIENT.NS", "Cyient Ltd.", "IT", "SMALL"),
    ("DCMSHRIRAM.NS", "DCM Shriram Ltd.", "Industrials", "SMALL"),
    ("DOMS.NS", "DOMS Industries Ltd.", "FMCG", "SMALL"),
    ("DATAPATTNS.NS", "Data Patterns (India) Ltd.", "Industrials", "SMALL"),
    ("DEEPAKFERT.NS", "Deepak Fertilisers & Petrochemicals Corp. Ltd.", "Chemicals", "SMALL"),
    ("DEEPAKNTR.NS", "Deepak Nitrite Ltd.", "Chemicals", "SMALL"),
    ("DELHIVERY.NS", "Delhivery Ltd.", "Industrials", "SMALL"),
    ("DEVYANI.NS", "Devyani International Ltd.", "ConsumerDisc", "SMALL"),
    ("LALPATHLAB.NS", "Dr. Lal Path Labs Ltd.", "Pharma", "SMALL"),
    ("EIDPARRY.NS", "E.I.D. Parry (India) Ltd.", "Chemicals", "SMALL"),
    ("EIHOTEL.NS", "EIH Ltd.", "ConsumerDisc", "SMALL"),
    ("ELECON.NS", "Elecon Engineering Co. Ltd.", "Industrials", "SMALL"),
    ("ELGIEQUIP.NS", "Elgi Equipments Ltd.", "Industrials", "SMALL"),
    ("EMAMILTD.NS", "Emami Ltd.", "FMCG", "SMALL"),
    ("EMCURE.NS", "Emcure Pharmaceuticals Ltd.", "Healthcare", "SMALL"),
    ("EMMVEE.NS", "Emmvee Photovoltaic Power Ltd.", "Capital Goods", "SMALL"),
    ("ENGINERSIN.NS", "Engineers India Ltd.", "Industrials", "SMALL"),
    ("ERIS.NS", "Eris Lifesciences Ltd.", "Pharma", "SMALL"),
    ("FACT.NS", "Fertilisers and Chemicals Travancore Ltd.", "Chemicals", "SMALL"),
    ("FINCABLES.NS", "Finolex Cables Ltd.", "Industrials", "SMALL"),
    ("FSL.NS", "Firstsource Solutions Ltd.", "Industrials", "SMALL"),
    ("FIVESTAR.NS", "Five-Star Business Finance Ltd.", "Financials", "SMALL"),
    ("FORCEMOT.NS", "Force Motors Ltd.", "Automobile and Auto Components", "SMALL"),
    ("GABRIEL.NS", "Gabriel India Ltd.", "Automobile and Auto Components", "SMALL"),
    ("GALLANTT.NS", "Gallantt Ispat Ltd.", "Capital Goods", "SMALL"),
    ("GRSE.NS", "Garden Reach Shipbuilders & Engineers Ltd.", "Industrials", "SMALL"),
    ("GILLETTE.NS", "Gillette India Ltd.", "FMCG", "SMALL"),
    ("GLAND.NS", "Gland Pharma Ltd.", "Pharma", "SMALL"),
    ("GODIGIT.NS", "Go Digit General Insurance Ltd.", "Financial Services", "SMALL"),
    ("GPIL.NS", "Godawari Power & Ispat Ltd.", "Industrials", "SMALL"),
    ("GRANULES.NS", "Granules India Ltd.", "Pharma", "SMALL"),
    ("GRAPHITE.NS", "Graphite India Ltd.", "Industrials", "SMALL"),
    ("GRAVITA.NS", "Gravita India Ltd.", "Metals & Mining", "SMALL"),
    ("GESHIP.NS", "Great Eastern Shipping Co. Ltd.", "Industrials", "SMALL"),
    ("GMDCLTD.NS", "Gujarat Mineral Development Corporation Ltd.", "Metals", "SMALL"),
    ("HEG.NS", "H.E.G. Ltd.", "Industrials", "SMALL"),
    ("HBLENGINE.NS", "HBL Engineering Ltd.", "Auto", "SMALL"),
    ("HFCL.NS", "HFCL Ltd.", "Telecom", "SMALL"),
    ("HSCL.NS", "Himadri Speciality Chemical Ltd.", "Chemicals", "SMALL"),
    ("HINDCOPPER.NS", "Hindustan Copper Ltd.", "Metals", "SMALL"),
    ("HOMEFIRST.NS", "Home First Finance Company India Ltd.", "Financials", "SMALL"),
    ("HONASA.NS", "Honasa Consumer Ltd.", "FMCG", "SMALL"),
    ("IDBI.NS", "IDBI Bank Ltd.", "Financials", "SMALL"),
    ("IFCI.NS", "IFCI Ltd.", "Financials", "SMALL"),
    ("IIFL.NS", "IIFL Finance Ltd.", "Financials", "SMALL"),
    ("IRB.NS", "IRB Infrastructure Developers Ltd.", "Industrials", "SMALL"),
    ("IRCON.NS", "IRCON International Ltd.", "Industrials", "SMALL"),
    ("ITI.NS", "ITI Ltd.", "Telecom", "SMALL"),
    ("INDGN.NS", "Indegene Ltd.", "Healthcare", "SMALL"),
    ("INDIACEM.NS", "India Cements Ltd.", "Cement", "SMALL"),
    ("INDIAMART.NS", "Indiamart Intermesh Ltd.", "ConsumerDisc", "SMALL"),
    ("IEX.NS", "Indian Energy Exchange Ltd.", "Financials", "SMALL"),
    ("IOB.NS", "Indian Overseas Bank", "Financials", "SMALL"),
    ("IGL.NS", "Indraprastha Gas Ltd.", "Energy", "SMALL"),
    ("INOXWIND.NS", "Inox Wind Ltd.", "Industrials", "SMALL"),
    ("INTELLECT.NS", "Intellect Design Arena Ltd.", "IT", "SMALL"),
    ("IGIL.NS", "International Gemological Institute Ltd.", "Services", "SMALL"),
    ("IKS.NS", "Inventurus Knowledge Solutions Ltd.", "Information Technology", "SMALL"),
    ("JBMA.NS", "JBM Auto Ltd.", "Auto", "SMALL"),
    ("JKTYRE.NS", "JK Tyre & Industries Ltd.", "Automobile and Auto Components", "SMALL"),
    ("JMFINANCIL.NS", "JM Financial Ltd.", "Financials", "SMALL"),
    ("JSWCEMENT.NS", "JSW Cement Ltd.", "Construction Materials", "SMALL"),
    ("JSWDULUX.NS", "JSW Dulux Ltd.", "Consumer Durables", "SMALL"),
    ("JAINREC.NS", "Jain Resource Recycling Ltd.", "Metals & Mining", "SMALL"),
    ("JPPOWER.NS", "Jaiprakash Power Ventures Ltd.", "Power", "SMALL"),
    ("J&KBANK.NS", "Jammu & Kashmir Bank Ltd.", "Financials", "SMALL"),
    ("JINDALSAW.NS", "Jindal Saw Ltd.", "Industrials", "SMALL"),
    ("JUBLINGREA.NS", "Jubilant Ingrevia Ltd.", "Chemicals", "SMALL"),
    ("JUBLPHARMA.NS", "Jubilant Pharmova Ltd.", "Pharma", "SMALL"),
    ("JWL.NS", "Jupiter Wagons Ltd.", "Industrials", "SMALL"),
    ("JYOTICNC.NS", "Jyoti CNC Automation Ltd.", "Capital Goods", "SMALL"),
    ("KAJARIACER.NS", "Kajaria Ceramics Ltd.", "ConsumerDisc", "SMALL"),
    ("KPIL.NS", "Kalpataru Projects International Ltd.", "Industrials", "SMALL"),
    ("KARURVYSYA.NS", "Karur Vysya Bank Ltd.", "Financials", "SMALL"),
    ("KAYNES.NS", "Kaynes Technology India Ltd.", "Industrials", "SMALL"),
    ("KEC.NS", "Kec International Ltd.", "Construction", "SMALL"),
    ("KFINTECH.NS", "Kfin Technologies Ltd.", "Financials", "SMALL"),
    ("KIRLOSENG.NS", "Kirloskar Oil Eng Ltd.", "Capital Goods", "SMALL"),
    ("KIMS.NS", "Krishna Institute of Medical Sciences Ltd.", "Pharma", "SMALL"),
    ("LTFOODS.NS", "LT Foods Ltd.", "Fast Moving Consumer Goods", "SMALL"),
    ("LATENTVIEW.NS", "Latent View Analytics Ltd.", "IT", "SMALL"),
    ("THELEELA.NS", "Leela Palaces Hotels & Resorts Ltd.", "Consumer Services", "SMALL"),
    ("LEMONTREE.NS", "Lemon Tree Hotels Ltd.", "ConsumerDisc", "SMALL"),
    ("MMTC.NS", "MMTC Ltd.", "Industrials", "SMALL"),
    ("MGL.NS", "Mahanagar Gas Ltd.", "Energy", "SMALL"),
    ("MANAPPURAM.NS", "Manappuram Finance Ltd.", "Financials", "SMALL"),
    ("MRPL.NS", "Mangalore Refinery & Petrochemicals Ltd.", "Energy", "SMALL"),
    ("MEESHO.NS", "Meesho Ltd.", "Consumer Services", "SMALL"),
    ("MINDACORP.NS", "Minda Corporation Ltd.", "Auto", "SMALL"),
    ("MSUMI.NS", "Motherson Sumi Wiring India Ltd.", "Auto", "SMALL"),
    ("NATCOPHARM.NS", "NATCO Pharma Ltd.", "Pharma", "SMALL"),
    ("NBCC.NS", "NBCC (India) Ltd.", "Industrials", "SMALL"),
    ("NCC.NS", "NCC Ltd.", "Industrials", "SMALL"),
    ("NSLNISP.NS", "NMDC Steel Ltd.", "Metals", "SMALL"),
    ("NH.NS", "Narayana Hrudayalaya Ltd.", "Pharma", "SMALL"),
    ("NAVA.NS", "Nava Ltd.", "Power", "SMALL"),
    ("NAVINFLUOR.NS", "Navin Fluorine International Ltd.", "Chemicals", "SMALL"),
    ("NETWEB.NS", "Netweb Technologies India Ltd.", "Information Technology", "SMALL"),
    ("NEULANDLAB.NS", "Neuland Laboratories Ltd.", "Healthcare", "SMALL"),
    ("NEWGEN.NS", "Newgen Software Technologies Ltd.", "Information Technology", "SMALL"),
    ("NIVABUPA.NS", "Niva Bupa Health Insurance Company Ltd.", "Financial Services", "SMALL"),
    ("NUVAMA.NS", "Nuvama Wealth Management Ltd.", "Financial Services", "SMALL"),
    ("NUVOCO.NS", "Nuvoco Vistas Corporation Ltd.", "Construction Materials", "SMALL"),
    ("OLAELEC.NS", "Ola Electric Mobility Ltd.", "Automobile and Auto Components", "SMALL"),
    ("OLECTRA.NS", "Olectra Greentech Ltd.", "Automobile and Auto Components", "SMALL"),
    ("ONESOURCE.NS", "Onesource Specialty Pharma Ltd.", "Healthcare", "SMALL"),
    ("PCBL.NS", "PCBL Chemical Ltd.", "Chemicals", "SMALL"),
    ("PGEL.NS", "PG Electroplast Ltd.", "Consumer Durables", "SMALL"),
    ("PNBHOUSING.NS", "PNB Housing Finance Ltd.", "Financials", "SMALL"),
    ("PTCIL.NS", "PTC Industries Ltd.", "Capital Goods", "SMALL"),
    ("PVRINOX.NS", "PVR INOX Ltd.", "ConsumerDisc", "SMALL"),
    ("PARADEEP.NS", "Paradeep Phosphates Ltd.", "Chemicals", "SMALL"),
    ("PFIZER.NS", "Pfizer Ltd.", "Healthcare", "SMALL"),
    ("PWL.NS", "Physicswallah Ltd.", "Consumer Services", "SMALL"),
    ("PINELABS.NS", "Pine Labs Ltd.", "Financial Services", "SMALL"),
    ("PIRAMALFIN.NS", "Piramal Finance Ltd.", "Financial Services", "SMALL"),
    ("PPLPHARMA.NS", "Piramal Pharma Ltd.", "Healthcare", "SMALL"),
    ("POLYMED.NS", "Poly Medicure Ltd.", "Healthcare", "SMALL"),
    ("POONAWALLA.NS", "Poonawalla Fincorp Ltd.", "Financial Services", "SMALL"),
    ("PFOCUS.NS", "Prime Focus Ltd.", "Media Entertainment & Publication", "SMALL"),
    ("RRKABEL.NS", "R R Kabel Ltd.", "Capital Goods", "SMALL"),
    ("RBLBANK.NS", "RBL Bank Ltd.", "Financial Services", "SMALL"),
    ("RHIM.NS", "RHI MAGNESITA INDIA LTD.", "Capital Goods", "SMALL"),
    ("RITES.NS", "RITES Ltd.", "Construction", "SMALL"),
    ("RAILTEL.NS", "Railtel Corporation Of India Ltd.", "Telecommunication", "SMALL"),
    ("RAINBOW.NS", "Rainbow Childrens Medicare Ltd.", "Healthcare", "SMALL"),
    ("RKFORGE.NS", "Ramkrishna Forgings Ltd.", "Metals", "SMALL"),
    ("REDINGTON.NS", "Redington Ltd.", "Services", "SMALL"),
    ("RPOWER.NS", "Reliance Power Ltd.", "Power", "SMALL"),
    ("SBFC.NS", "SBFC Finance Ltd.", "Financial Services", "SMALL"),
    ("SAGILITY.NS", "Sagility Ltd.", "Information Technology", "SMALL"),
    ("SAILIFE.NS", "Sai Life Sciences Ltd.", "Healthcare", "SMALL"),
    ("SAMMAANCAP.NS", "Sammaan Capital Ltd.", "Financial Services", "SMALL"),
    ("SAPPHIRE.NS", "Sapphire Foods India Ltd.", "ConsumerDisc", "SMALL"),
    ("SARDAEN.NS", "Sarda Energy and Minerals Ltd.", "Metals & Mining", "SMALL"),
    ("SAREGAMA.NS", "Saregama India Ltd", "Media Entertainment & Publication", "SMALL"),
    ("SCHNEIDER.NS", "Schneider Electric Infrastructure Ltd.", "Capital Goods", "SMALL"),
    ("SCI.NS", "Shipping Corporation of India Ltd.", "Services", "SMALL"),
    ("SHYAMMETL.NS", "Shyam Metalics and Energy Ltd.", "Capital Goods", "SMALL"),
    ("SIGNATURE.NS", "Signatureglobal (India) Ltd.", "Realty", "SMALL"),
    ("SOBHA.NS", "Sobha Ltd.", "Realty", "SMALL"),
    ("SONACOMS.NS", "Sona BLW Precision Forgings Ltd.", "Auto", "SMALL"),
    ("SONATSOFTW.NS", "Sonata Software Ltd.", "Information Technology", "SMALL"),
    ("STARHEALTH.NS", "Star Health and Allied Insurance Company Ltd.", "Financial Services", "SMALL"),
    ("SUMICHEM.NS", "Sumitomo Chemical India Ltd.", "Chemicals", "SMALL"),
    ("SUNTV.NS", "Sun TV Network Ltd.", "ConsumerDisc", "SMALL"),
    ("SPLPETRO.NS", "Supreme Petrochem Ltd.", "Chemicals", "SMALL"),
    ("SWANCORP.NS", "Swan Corp Ltd.", "Chemicals", "SMALL"),
    ("SYNGENE.NS", "Syngene International Ltd.", "Healthcare", "SMALL"),
    ("SYRMA.NS", "Syrma SGS Technology Ltd.", "Capital Goods", "SMALL"),
    ("TBOTEK.NS", "TBO Tek Ltd.", "Consumer Services", "SMALL"),
    ("TATACHEM.NS", "Tata Chemicals Ltd.", "Chemicals", "SMALL"),
    ("TATATECH.NS", "Tata Technologies Ltd.", "Information Technology", "SMALL"),
    ("TTML.NS", "Tata Teleservices (Maharashtra) Ltd.", "Telecommunication", "SMALL"),
    ("TECHNOE.NS", "Techno Electric & Engineering Company Ltd.", "Construction", "SMALL"),
    ("TEGA.NS", "Tega Industries Ltd.", "Capital Goods", "SMALL"),
    ("TEJASNET.NS", "Tejas Networks Ltd.", "Telecommunication", "SMALL"),
    ("TENNIND.NS", "Tenneco Clean Air India Ltd.", "Automobile and Auto Components", "SMALL"),
    ("RAMCOCEM.NS", "The Ramco Cements Ltd.", "Construction Materials", "SMALL"),
    ("TIMKEN.NS", "Timken India Ltd.", "Capital Goods", "SMALL"),
    ("TITAGARH.NS", "Titagarh Rail Systems Ltd.", "Capital Goods", "SMALL"),
    ("TARIL.NS", "Transformers And Rectifiers (India) Ltd.", "Capital Goods", "SMALL"),
    ("TRAVELFOOD.NS", "Travel Food Services Ltd.", "Consumer Services", "SMALL"),
    ("TRIDENT.NS", "Trident Ltd.", "Textiles", "SMALL"),
    ("TRITURBINE.NS", "Triveni Turbine Ltd.", "Capital Goods", "SMALL"),
    ("UCOBANK.NS", "UCO Bank", "Financial Services", "SMALL"),
    ("UTIAMC.NS", "UTI Asset Management Company Ltd.", "Financial Services", "SMALL"),
    ("URBANCO.NS", "Urban Company Ltd.", "Consumer Services", "SMALL"),
    ("USHAMART.NS", "Usha Martin Ltd.", "Capital Goods", "SMALL"),
    ("VTL.NS", "Vardhman Textiles Ltd.", "Textiles", "SMALL"),
    ("VIJAYA.NS", "Vijaya Diagnostic Centre Ltd.", "Healthcare", "SMALL"),
    ("WELCORP.NS", "Welspun Corp Ltd.", "Capital Goods", "SMALL"),
    ("WELSPUNLIV.NS", "Welspun Living Ltd.", "Textiles", "SMALL"),
    ("WHIRLPOOL.NS", "Whirlpool of India Ltd.", "ConsumerDisc", "SMALL"),
    ("WOCKPHARMA.NS", "Wockhardt Ltd.", "Healthcare", "SMALL"),
    ("ZFCVINDIA.NS", "ZF Commercial Vehicle Control Systems India Ltd.", "Automobile and Auto Components", "SMALL"),
    ("ZEEL.NS", "Zee Entertainment Enterprises Ltd.", "ConsumerDisc", "SMALL"),
    ("ZENTEC.NS", "Zen Technologies Ltd.", "Industrials", "SMALL"),
    ("ZENSARTECH.NS", "Zensar Technolgies Ltd.", "Information Technology", "SMALL"),
    ("ZYDUSWELL.NS", "Zydus Wellness Ltd.", "Fast Moving Consumer Goods", "SMALL"),
    ("ECLERX.NS", "eClerx Services Ltd.", "Services", "SMALL"),
]
